# =========================
# Site identity
# =========================
title:               "fomties™"
description:         "everyone's pretending to have it figured out."
url:                 "https://www.fomties.com"   # <- change if different
baseurl:             ""                            # subpath, e.g. "/blog" (empty if at root)

author:
  name:  "fomties"
  email: "hello@fomties.com"

# Optional social (used in <head> and footer/elsewhere if you reference them)
social:
  twitter:  "fomties"
  instagram: "fomties"
  github:   "fomties"
  x:        "fomties"   # alias if you reference it

# -----------------------------
# Build
# -----------------------------
permalink:           pretty
relative_permalinks: false

include:             ["_pages"]

use_html_extension:  false

open_external_links_in_new_tab: true
embed_tweets:        false

timezone: "UTC"

# -----------------------------
# Plugins
# -----------------------------
plugins:
  - jekyll-last-modified-at
  - jekyll-feed

# jekyll-feed settings: only publish blog posts (not notes) to /feed.xml
feed:
  path: feed
  # By default jekyll-feed only includes posts.
  # If you ever add custom collections to the feed, list them here:
  # collections:
  #   - posts

# -----------------------------
# Sass/CSS
# -----------------------------
sass:
  sass_dir: _sass
  style:    :compressed

# -----------------------------
# Collections
# -----------------------------
collections:
  notes:
    output: true
    permalink: /:slug

# -----------------------------
# Defaults (layouts per type)
# -----------------------------
defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"

  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"

  - scope:
      path: "_posts/*"
    values:
      layout: "post"
      # Optional: set categories/tags defaults here if you like
      # categories: ["writing"]

# -----------------------------
# Markdown / excerpts (optional nice defaults)
# -----------------------------
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

# Show teaser/preview by splitting content with this marker
excerpt_separator: "\n\n<!--more-->\n\n"
